name: Update release version.
on:
  release:
    types: [published]


jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bumpversion release version.
        uses: tj-actions/bumpversion@v7
        id: bumpversion
        with:
          pattern: 'tj-actions/bumpversion@'
          paths: |
            README.md
            .github/workflows/sync-release-version.yml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: "master"
          title: "Upgraded to ${{ steps.bumpversion.outputs.new_version }}"
          branch: "upgrade-to-${{ steps.bumpversion.outputs.new_version }}"
          commit-message: "Upgraded from ${{ steps.bumpversion.outputs.old_version }} -> ${{ steps.bumpversion.outputs.new_version }}"
          body: "View [CHANGES](https://github.com/${{ github.repository }}/compare/v${{ steps.bumpversion.outputs.old_version }}...v${{ steps.bumpversion.outputs.new_version }})"
          reviewers: "jackton1"
